# Generated by Django 3.1.1 on 2020-09-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_raffle_raffleparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='name',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
