# Generated by Django 3.1.1 on 2020-09-25 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_raffle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='api.cohort'),
        ),
    ]
