# Generated by Django 3.1.1 on 2020-12-02 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201202_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
